bnb-chain/greenfield-challenger

- .github/CHANGELOG.md
This release launches the Challenger Service.        
Change log:  
* [#19](https://github.com/bnb-chain/greenfield-challenger/pull/19) fix: added error logs  
* [#20](https://github.com/bnb-chain/greenfield-challenger/pull/20) fix: fix hash verifier issue
* [#21](https://github.com/bnb-chain/greenfield-challenger/pull/21) refactor: refine some codes
* [#22](https://github.com/bnb-chain/greenfield-challenger/pull/22) refactor: refine codes to skip events and query heartbeat interval from blockchain
* [#23](https://github.com/bnb-chain/greenfield-challenger/pull/23) add lint and gosec workflows
* [#24](https://github.com/bnb-chain/greenfield-challenger/pull/24) doc: add deployment documentation 
* [#25](https://github.com/bnb-chain/greenfield-challenger/pull/25) license: add opensource …
> release: draft release v0.0.1  

- .github/CHANGELOG.md
This is a pre-release. The go-sdk module and it's relevant dependencies are updated to use their pre-release alpha versions.
Changelog:  
* [#44](https://github.com/bnb-chain/greenfield-challenger/pull/44) chore: upgrade dependencies      
Please refer to detailed PRs
* There are no notable changes
> release: draft release v0.0.2-alpha.1

- CHANGELOG.md
This is a maintenance release that updates the service to adapt to it's updated dependencies and code refactoring.    
Change log:  
* [#47](https://github.com/bnb-chain/greenfield-challenger/pull/47) feat: adapt to new go-sdk and greenfield version  
Please refer to detailed PRs
* There are no notable changes
> release: draft release for v0.0.2  

- attest/attest_monitor.go
- db/model/event.go
- verifier/hash_verifier.go
Resolve an error that was caused by placing the BucketDeleted status in VerifyStatus  
It was causing the service to crash since it couldn't create votes based on that particular status  
none
none
> fix: remove bucketdeleted status from verifystatus and place in eventstatus instead  

- CHANGELOG.md
This is a hotfix release that resolves a bug that was caused by an invalid verification status.
* [#51](https://github.com/bnb-chain/greenfield-challenger/pull/51) fix: remove bucketdeleted status from verifystatus and place in eventstatus instead  
Please refer to the PRs for detailed information.  
none
> release: draft release for v0.0.2-hotfix  

- attest/attest_monitor.go
- db/model/event.go
- verifier/hash_verifier.go
this status is no longer required  
cleanup unused status  
none   
none
> fix: remove bucketdeleted status

- app/app.go
- attest/attest_monitor.go
- config/config.go
- executor/executor.go
- go.mod
- logging/log.go
- metrics/metrics.go
- monitor/monitor.go
- submitter/tx_submitter.go
- verifier/hash_verifier.go
- verifier/hash_verifier_test.go
- vote/data_provider.go
- vote/vote_broadcaster.go
- vote/vote_collator.go
- vote/vote_collector.go
Adding a metrics service  
To help monitor performance and detect errors  
none  
none
> feat: add metrics

- app/app.go
- config/config.go
- db/model/event.go
- executor/executor.go
- submitter/tx_submitter.go
- verifier/hash_verifier.go
- verifier/hash_verifier_test.go
The inturn submitter might change after a challenge is submitted but not confirmed to be attested, resulting in the next submitter to submit the same challenge.  
To update the event status correctly.  
none  
Added a new event status for DuplicatedSlash. Stop attempting to submit if recently submitted.  
none
> fix: attest monitor missing attested challenges

- .github/workflows/docker-release.yml
ci: add docker job for tag releasing
n/a
Notable changes:
* ci
> ci: add docker job for tag releasing

- CHANGELOG.md
This release updates the dependencies to adapt to Greenfield v0.2.4 and contains 1 new feature.  
Features:  
* [#73](https://github.com/bnb-chain/greenfield-challenger/pull/73) feat: enable using env vars for config
Chores:
* [#76](https://github.com/bnb-chain/greenfield-challenger/pull/76) chore: clean up unused code and update dependencies
CI:  
* [#75](https://github.com/bnb-chain/greenfield-challenger/pull/75) ci: add docker job for tag releasing
* [#74](https://github.com/bnb-chain/greenfield-challenger/pull/74) ci: Create Dockerfile.distroless
Please refer to the PRs for detailed information.  
none
> release: draft release for v0.0.5

- CHANGELOG.md
This release updates the dependencies to adapt to Greenfield v0.2.6 and adds a bugfix to handle events where components cannot be fetched successfully for hash verification.  
Bugfixes:  
* [#87](https://github.com/bnb-chain/greenfield-challenger/pull/87) fix: handle events where components cannot be fetched successfully for hash verification
Please refer to individual PRs for detailed information.  
none
> release: draft release for v0.0.7  

- executor/executor.go
- go.mod
- go.sum
Update go-sdk to use challenge v2 version.
Update api
NA
* use v2 chellange api
> chore: update challenge api to v2 version

- go.mod
- go.sum
Update greenfield go sdk.
Chore
NA
* go.mod
> chore: update greenfield go sdk

- executor/executor.go
Fix error with get latest block  
It was causing some issues with fetching events from db  
none  
none
> fix: fix error with get latest block

- app/app.go
- executor/executor.go
- monitor/monitor.go
- submitter/tx_submitter.go
- verifier/hash_verifier.go
- vote/vote_broadcaster.go
- vote/vote_collator.go
Fix an issue where the latest cached height would return 0
To get the correct latest block height 
none 
none
> fix: the latest cached height could be zero

- CHANGELOG.md
This is a hotfix release to resolve bugs that were found during testing.
1. Error response that appears when challenging large objects.
2. Error handling when the service fails to get the latest block height from the blockchain.  
Bugfix:  
[#98](https://github.com/bnb-chain/greenfield-challenger/pull/98) fix: the latest cached height could be zero 
[#97](https://github.com/bnb-chain/greenfield-challenger/pull/97) fix: fix error with get latest block 
[#95](https://github.com/bnb-chain/greenfield-challenger/pull/95) fix: added a new status VerificationFailed
Chores:  
[#94](https://github.com/bnb-chain/greenfield-challenger/pull/94) chore: update greenfield go sdk 
[#93](https://github.com/bnb-chain/greenfield-challenger/pull/93) chore: update challenge api to v2 version  
Please refer to …
> release: draft release for v1.0.1

- config/config.go
- config/config.json
- executor/executor.go
- metrics/metrics.go
- submitter/tx_submitter.go
- verifier/const.go
- verifier/hash_verifier.go
Add sp metrics for internal/external sp to better identify the source of the errors.  
To segregate the issues and create alerts for them.  
none  
none
> feat: add sp metrics for internal/external sp   

- common/error.go
- verifier/hash_verifier.go
A precheck was set in place to prevent an event from being processed if it's expired or the SP has been recently slashed. It was not handling cases correctly where the SP has been recently slashed.
This issue needs to be resolved to prevent the challenger services from submitting the events for attestation. The attestation would not go through but it would cost gas to send the transaction.  
none
none
> fix: precheck not correctly handling cases where duplicated slashing is found  

- executor/client.go
- monitor/monitor.go
This pr will 
* add timeout when selecting gnfd clients
* add error logs
Bug fix
NA
* client
> fix: add timeout when selecting clients

- app/app.go
- config/utils.go
Support reading db username/password from env.
chore
```
export DB_USERNAME=dbuser
export DB_PASSWORD=dbpass
```
* NA
> chore: support reading db config from env
